export const AVTORIZATION_USER = 'AVTORIZATION_USER'
export const GET_INPUT_VALUE = 'GET_INPUT_VALUE';
export const CHECK_STATE_COMPONENT = 'CHECK_STATE_COMPONENT';
export const GET_DATA ='GET_DATA';
export const STATUS_LIST ='STATUS_LIST';
export const STATUS_TABLE ='STATUS_TABLE';
export const VIEWS ='VIEWS';
export const STATUS_FAVORITES = 'STATUS_FAVORITES';
export const DATA_FAVORITES = 'DATA_FAVORITES';

export const NAME_REQUEST = 'NAME_REQUEST';
export const ORDER_REQUEST = 'ORDER_REQUEST';
export const MAX_VALUE_COUNT_REQUEST = 'MAX_VALUE_COUNT_REQUEST';

export const COUNT = 'COUNT'


